require:
  - rubocop-capybara

  - rubocop-rspec_rails
  - rubocop-erb
plugins:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'config/**/*'
    - 'db/**/*'
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Lint/MissingSuper:
  Enabled: true
  Exclude:
    - app/services/**/*
RSpec/NestedGroups:
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    - 'app/**/*/api/v1/**/*'